CREATE TABLE IF NOT EXISTS PROJECT_TYPE (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ENCODER_TYPE (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS CODEC (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ENCODER_MODES (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS QUALITY (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS GAMUT (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS TOPOLOGY (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS RESOLUTION (
    ID INT PRIMARY KEY,
    X INT,
    Y INT
);

CREATE TABLE IF NOT EXISTS TRANSMISSION_CONDITION (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    LOWER_BOUND INT,
    UPPER_BOUND INT
);

CREATE TABLE IF NOT EXISTS VIDEO_FILE (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS VIDEO_FILE_RESOLUTION (
    VIDEO_ID INT,
    RESOLUTION_ID INT,
    CONSTRAINT VIDEO_FILE_RESOLUTION_VIDEO_ID_FK FOREIGN KEY (VIDEO_ID)
    REFERENCES VIDEO_FILE(ID),
    CONSTRAINT RESOLUTION_FK FOREIGN KEY (RESOLUTION_ID)
    REFERENCES RESOLUTION(ID),
    PRIMARY KEY(VIDEO_ID, RESOLUTION_ID)
);

CREATE TABLE IF NOT EXISTS VIDEO_FILE_FRAME_RATE (
    VIDEO_ID INT,
    FRAME_RATE_ID INT,
    CONSTRAINT VIDEO_FILE_FRAME_RATE_VIDEO_ID_FK FOREIGN KEY (VIDEO_ID)
    REFERENCES VIDEO_FILE(ID),
    CONSTRAINT FRAME_RATE_FK FOREIGN KEY (FRAME_RATE_ID)
    REFERENCES FRAME_RATE(ID),
    PRIMARY KEY(VIDEO_ID, FRAME_RATE_ID)
);

CREATE TABLE IF NOT EXISTS VIDEO_FILE_DEPTH (
    VIDEO_ID INT,
    DEPTH_ID INT,
    CONSTRAINT VIDEO_FILE_DEPTH_VIDEO_ID_FK FOREIGN KEY (VIDEO_ID)
    REFERENCES VIDEO_FILE(ID),
    CONSTRAINT DEPTH_FK FOREIGN KEY (DEPTH_ID)
    REFERENCES DEPTH(ID),
    PRIMARY KEY(VIDEO_ID, DEPTH_ID)
);

CREATE TABLE IF NOT EXISTS RESOLUTION (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS FRAME_RATE (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS DEPTH (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255)
);